version: '3.8'

services:
  web:
    build: .
    image: simple-web-app:java21
    ports:
      - "8080-8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    deploy:
      replicas: 2